-- MySQL Script generated by MySQL Workbench
-- Tue May 19 12:43:29 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema main
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema main
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `main` DEFAULT CHARACTER SET latin1 ;
USE `main` ;

-- -----------------------------------------------------
-- Table `main`.`Sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `main`.`Sessions` (
  `session_id` VARCHAR(32) NOT NULL DEFAULT '',
  `expires` DATETIME NULL DEFAULT NULL,
  `data` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`session_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `main`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `main`.`location` (
  `location_id` INT(11) NOT NULL AUTO_INCREMENT,
  `ip_address` VARCHAR(64) NOT NULL,
  `latitude` DOUBLE NULL DEFAULT NULL,
  `longitude` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`location_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `main`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `main`.`address` (
  `address_id` INT(11) NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(64) NOT NULL,
  `city` VARCHAR(64) NOT NULL,
  `state` VARCHAR(48) NOT NULL,
  `zip_code` VARCHAR(24) NOT NULL,
  `location_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`address_id`),
  INDEX `location_id` (`location_id` ASC),
  CONSTRAINT `address_ibfk_1`
    FOREIGN KEY (`location_id`)
    REFERENCES `main`.`location` (`location_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `main`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `main`.`company` (
  `company_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `address_id` INT(11) NOT NULL,
  `email` VARCHAR(128) NOT NULL,
  `phone_number` VARCHAR(12) NOT NULL,
  `visit_fee` DECIMAL(5,2) NOT NULL,
  PRIMARY KEY (`company_id`),
  INDEX `address_id` (`address_id` ASC),
  CONSTRAINT `company_ibfk_1`
    FOREIGN KEY (`address_id`)
    REFERENCES `main`.`address` (`address_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `main`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `main`.`user` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_type` VARCHAR(64) NOT NULL,
  `first_name` VARCHAR(64) NOT NULL,
  `last_name` VARCHAR(64) NOT NULL,
  `email` VARCHAR(128) NOT NULL,
  `phone_number` VARCHAR(24) NOT NULL,
  `birthdate` VARCHAR(24) NOT NULL,
  `company_id` INT(11) NULL DEFAULT NULL,
  `license_number` VARCHAR(24) NULL DEFAULT NULL,
  `location_id` INT(11) NULL,
  `date_created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date_modified` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `salt` VARCHAR(255) NOT NULL,
  `hash` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `unique_email` (`email` ASC),
  INDEX `company_id` (`company_id` ASC),
  INDEX `location_id` (`location_id` ASC),
  CONSTRAINT `user_ibfk_1`
    FOREIGN KEY (`company_id`)
    REFERENCES `main`.`company` (`company_id`),
  CONSTRAINT `user_ibfk_2`
    FOREIGN KEY (`location_id`)
    REFERENCES `main`.`location` (`location_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `main`.`service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `main`.`service` (
  `service_id` INT(11) NULL AUTO_INCREMENT,
  `company_id` INT(11) NOT NULL,
  `name` VARCHAR(48) NOT NULL,
  `description` VARCHAR(64) NOT NULL,
  `cost` DECIMAL(8,2) NOT NULL,
  `service_type` VARCHAR(48) NOT NULL,
  `service_duration` VARCHAR(48) NOT NULL,
  PRIMARY KEY (`service_id`),
  INDEX `fk_service_company1_idx` (`company_id` ASC),
  CONSTRAINT `fk_service_company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `main`.`company` (`company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `main`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `main`.`order` (
  `order_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `service_id` INT(11) NOT NULL,
  `total` DECIMAL(8,2) NOT NULL,
  `order_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `employee_id` INT(11) NULL,
  `reservation_notes` VARCHAR(255) NULL,
  `reservation_date` DATETIME NOT NULL,
  `reservation_status` VARCHAR(64) NOT NULL,
  `reservation_start` DATETIME NULL,
  `reservation_end` DATETIME NULL,
  `date_finished` VARCHAR(45) NULL,
  PRIMARY KEY (`order_id`),
  INDEX `user_id` (`user_id` ASC),
  INDEX `service_id` (`service_id` ASC),
  INDEX `employee_id` (`employee_id` ASC),
  CONSTRAINT `orders_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `main`.`user` (`user_id`),
  CONSTRAINT `orders_ibfk_2`
    FOREIGN KEY (`service_id`)
    REFERENCES `main`.`service` (`service_id`),
  CONSTRAINT `orders_ibfk_4`
    FOREIGN KEY (`employee_id`)
    REFERENCES `main`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `main`.`chat_message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `main`.`chat_message` (
  `chat_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `order_id` INT(11) NOT NULL,
  `message` VARCHAR(255) NOT NULL,
  `when` DATETIME NOT NULL,
  PRIMARY KEY (`chat_id`),
  INDEX `user_id` (`user_id` ASC),
  INDEX `order_id` (`order_id` ASC),
  CONSTRAINT `chat_message_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `main`.`user` (`user_id`),
  CONSTRAINT `chat_message_ibfk_2`
    FOREIGN KEY (`order_id`)
    REFERENCES `main`.`order` (`order_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `main`.`feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `main`.`feedback` (
  `feedback_id` INT NOT NULL AUTO_INCREMENT,
  `orders_id` INT(11) NOT NULL,
  `feedback_type` VARCHAR(24) NOT NULL,
  `rating` DECIMAL(5,2) NOT NULL,
  `comments` VARCHAR(2000) NOT NULL,
  PRIMARY KEY (`feedback_id`, `orders_id`),
  INDEX `fk_feedback_orders1_idx` (`orders_id` ASC),
  CONSTRAINT `fk_feedback_orders1`
    FOREIGN KEY (`orders_id`)
    REFERENCES `main`.`order` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `main`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `main`.`payment` (
  `payment_id` INT(11) NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(64) NOT NULL,
  `last_name` VARCHAR(64) NOT NULL,
  `order_id` INT(11) NOT NULL,
  `amount` DECIMAL(8,2) NOT NULL,
  `reciept` VARCHAR(400) NOT NULL,
  `payment_method` INT(11) NOT NULL,
  `payment_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`payment_id`),
  INDEX `order_id` (`order_id` ASC),
  CONSTRAINT `pay_ibfk_2`
    FOREIGN KEY (`order_id`)
    REFERENCES `main`.`order` (`order_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `main`.`user_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `main`.`user_address` (
  `user_id` INT(11) NOT NULL,
  `address_id` INT(11) NOT NULL,
  PRIMARY KEY (`user_id`, `address_id`),
  INDEX `fk_user_has_address_address1_idx` (`address_id` ASC),
  INDEX `fk_user_has_address_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_has_address_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `main`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_address_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `main`.`address` (`address_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
